loki:
  enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClassName: gp2
    size: 32Gi

promtail:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.7.0
  nodeSelector:
    eks.amazonaws.com/nodegroup: tools
  persistence:
    enabled: true
    storageClassName: gp2
    size: 32Gi
  service:
    type: ClusterIP
    protocol: TCP
    port: 80
    targetPort: 3000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - grafana-${stage}.${domain}
  grafana.ini:
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      root_url: https://grafana-${stage}.${domain}
    smtp:
      enabled: true
      host: ${smtp_host}
      user: ${smtp_user}
      password: ${smtp_password}
      skip_verify: true
      from_address: ${smtp_user}
      from_name: Grafana

prometheus:
  enabled: true
  server:
    nodeSelector:
      eks.amazonaws.com/nodegroup: tools
  pushgateway:
    nodeSelector:
      eks.amazonaws.com/nodegroup: tools
  alertmanager:
    enabled: true
    nodeSelector:
      eks.amazonaws.com/nodegroup: tools
